### PR TITLE
Updating for v9: from chai to tap testing framework

### PR DESCRIPTION
**Pull request by Ranieri93**
Hello! 
Here I tried to switch to tap as testing framework.
I know that is not needed to mark this dep as ready for the update, but it was not that much work, so I give it a shot.
Any suggestion is always welcomed!

### CODE REVIEW

**Comment by Ranieri93** [comment]
How should am I supposed to proceed with conflicts? Should I resolve them here? @jsumners

**Comment by jsumners** [comment]
Unfortunately, I think we will need to take a different approach on this one. There is a possibility that the Pino org as a whole could be included in the OpenJS Foundation. At this time projects in that org must rely on dependencies that use licenses from a short list of allowed licenses, and `tap` is moving to BlueOak without possibility of being dual licensed (https://github.com/tapjs/tapjs/issues/821#issuecomment-1721839895).

If you want to migrate the tests to something similar, I believe using https://nodejs.org/dist/latest-v18.x/docs/api/test.html will suffice.

**Comment by Ranieri93** [comment]
Thank you @jsumners, I'll try and use that instead.

**Comment by jsumners** [comment]
I appreciate the enthusiasm, but this item should probably be held off. See the updates I added yesterday on the overall tracking issue.

**Comment by Ranieri93** [comment]
Make sense, I'll close this PR then

**Pull request closed without merging**
